name: Publish Release
on:
  push:
    tags:
      - '*'
      - 'stable'
      - 'beta'
      - 'insider'
      - 'alpha'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set output
      id: vars
      run: |
        echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
        echo "version=$(git tag --points-at HEAD | grep v)" >> $GITHUB_OUTPUT
    - name: Create a Release
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
        echo '### 🚀 ${{ steps.vars.outputs.version }}' >> $GITHUB_STEP_SUMMARY
        echo '### 🚀 ${{ steps.vars.outputs.tag }}' >> $GITHUB_STEP_SUMMARY
      
